<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Update="xml\Genglvnd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\genglvnd.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\genheaders.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\gl.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\glx.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\glxproto.reserved.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\Makefile">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\README.adoc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\readme.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\readme.tex">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\reg.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\registry.rnc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\testesext.c">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\testglext.c">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\vendors.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\wgl.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xml\wgltypes.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
