function(nif_normalize_os_identifier INPUT_VALUE OUTPUT_NAME OUTPUT_DEFINE)
    string(TOLOWER "${INPUT_VALUE}" _nif_os)

    if(_nif_os STREQUAL "auto")
        string(TOLOWER "${CMAKE_SYSTEM_NAME}" _nif_system_name)
        if(_nif_system_name STREQUAL "windows")
            set(_nif_os "windows")
        elseif(_nif_system_name STREQUAL "linux")
            set(_nif_os "linux")
        endif()
    endif()

    if(_nif_os STREQUAL "windows")
        set(_nif_define NIF_OS_WINDOWS)
    elseif(_nif_os STREQUAL "linux")
        set(_nif_define NIF_OS_LINUX)
    else()
        message(FATAL_ERROR "Unsupported NIF_TARGET_OS='${INPUT_VALUE}'.")
    endif()

    set(${OUTPUT_NAME} "${_nif_os}" PARENT_SCOPE)
    set(${OUTPUT_DEFINE} "${_nif_define}" PARENT_SCOPE)
endfunction()

function(nif_normalize_arch_identifier INPUT_VALUE OUTPUT_NAME OUTPUT_DEFINE)
    string(TOLOWER "${INPUT_VALUE}" _nif_arch)

    if(_nif_arch STREQUAL "auto")
        string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _nif_processor)
        if(_nif_processor MATCHES "^(amd64|x86_64|x64)$")
            set(_nif_arch "x86_64")
        elseif(_nif_processor MATCHES "^(arm64|aarch64)$")
            set(_nif_arch "arm64")
        elseif(_nif_processor STREQUAL "riscv64")
            set(_nif_arch "riscv64")
        elseif(_nif_processor MATCHES "^(ppc64le|powerpc64le)$")
            set(_nif_arch "ppc64le")
        else()
            message(FATAL_ERROR "Unable to infer ISA from CMAKE_SYSTEM_PROCESSOR='${CMAKE_SYSTEM_PROCESSOR}'. Set NIF_TARGET_ARCH explicitly.")
        endif()
    endif()

    if(_nif_arch STREQUAL "x86_64")
        set(_nif_define NIF_ARCH_X86_64)
    elseif(_nif_arch STREQUAL "arm64")
        set(_nif_define NIF_ARCH_ARM64)
    elseif(_nif_arch STREQUAL "riscv64")
        set(_nif_define NIF_ARCH_RISCV64)
    elseif(_nif_arch STREQUAL "ppc64le")
        set(_nif_define NIF_ARCH_PPC64le)
    else()
        message(FATAL_ERROR "Unsupported NIF_TARGET_ARCH='${INPUT_VALUE}'.")
    endif()

    set(${OUTPUT_NAME} "${_nif_arch}" PARENT_SCOPE)
    set(${OUTPUT_DEFINE} "${_nif_define}" PARENT_SCOPE)
endfunction()

function(nif_resolve_target_identifiers INPUT_OS INPUT_ARCH OUTPUT_OS_NAME OUTPUT_OS_DEFINE OUTPUT_ARCH_NAME OUTPUT_ARCH_DEFINE)
    nif_normalize_os_identifier("${INPUT_OS}" _nif_os_name _nif_os_define)
    nif_normalize_arch_identifier("${INPUT_ARCH}" _nif_arch_name _nif_arch_define)

    set(${OUTPUT_OS_NAME} "${_nif_os_name}" PARENT_SCOPE)
    set(${OUTPUT_OS_DEFINE} "${_nif_os_define}" PARENT_SCOPE)
    set(${OUTPUT_ARCH_NAME} "${_nif_arch_name}" PARENT_SCOPE)
    set(${OUTPUT_ARCH_DEFINE} "${_nif_arch_define}" PARENT_SCOPE)
endfunction()

function(nif_register_external_package TARGET PACKAGE_NAME PACKAGE_DIR)
    if(NOT TARGET ${TARGET})
        message(FATAL_ERROR "nif_register_external_package: target '${TARGET}' does not exist.")
    endif()

    if(EXISTS "${PACKAGE_DIR}")
        target_include_directories(${TARGET} PRIVATE "${PACKAGE_DIR}")
        message(STATUS "Registered external package '${PACKAGE_NAME}' include: ${PACKAGE_DIR}")
    else()
        message(FATAL_ERROR "External package directory not found: ${PACKAGE_DIR}")
    endif()
endfunction()

function(nif_link_external_binary_if_exists TARGET LIBRARY_PATH)
    if(EXISTS "${LIBRARY_PATH}")
        target_link_libraries(${TARGET} PRIVATE "${LIBRARY_PATH}")
        message(STATUS "Linked external binary: ${LIBRARY_PATH}")
    endif()
endfunction()
