<Project Sdk="Microsoft.NET.Sdk">



  <ItemGroup>
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nitload.Common\Nitload.Common.csproj" />
  </ItemGroup>

</Project>
