// -----------------------------------------------------------------------------
// file="TextRegexSourceGen.GenFile"
// Project: StgSharp
// Copyright (c) Nitload.
// SPDX-License-Identifier: MIT
// -----------------------------------------------------------------------------

using Microsoft.CodeAnalysis;
using StgSharp.RegularAnalysis.Abstraction;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace StgSharp.RegularAnalysis.Text
{
    internal partial class TextRegexSourceGen
    {

        public const string ROS_char = "global::System.ReadOnlySpan<char>";
        public const string Text_Regex = "global::StgSharp.RegularAnalysis.Text.TextRegex";

        private static readonly SymbolDisplayFormat TypeSourceFormat =
            SymbolDisplayFormat.FullyQualifiedFormat
                               .AddMiscellaneousOptions(
                                    SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

        private static string AsSource<T>()
        {
            Type t = typeof(T);
            return t.IsGenericType ? throw new InvalidOperationException() : $"global::{t.FullName}";
        }

        private static void GenerateRegexSourceFile(
                            SourceProductionContext context,
                            TextRegexBinding binding
        )
        {
            StringBuilder file_name_sb = new();
            SequenceEmitter<string> ce = new();
            SourceRecord gen_source = binding.Source;
            TypeSource type = binding.Source.ContainingType;

            _ = file_name_sb.Append(CultureInfo.InvariantCulture, $"{gen_source.NamespaceName}.");
            _ = ce.AppendLine($@"// <auto-generated/>")
                  .AppendLine($@"#nullable enable")
                  .AppendLine($@"using StgSharp.RegularAnalysis.Text;")
                  .AppendLine($@"using StgSharp.RegularAnalysis.Abstraction;")
                  .AppendLine($@"using System;")
                  .AppendLine($@"using System.Text;")
                  .AppendLine($@"using System.Threading.Tasks;")
                  .AppendLine()
                  .AppendLine($@"namespace {gen_source.NamespaceName};");

            string static_modifier;

            int brace_count = 0;
            do
            {
                _ = file_name_sb.Append(CultureInfo.InvariantCulture, $@"{type.TypeName}.");
                string declare_type = type.DeclType switch
                {
                    TypeKind.Class => "class",
                    TypeKind.Struct => "struct",
                    _ => throw new InvalidOperationException($"Unexpected type kind: {type.DeclType}"),
                };
                static_modifier = type.IsStatic ? "static" : string.Empty;
                _ = ce.AppendLine($@"{ToKeyword(type.Accessibility)} {static_modifier} partial {declare_type} {type.TypeName}")
                      .AppendLine("{");
                brace_count++;
                type = type.InnerType!;
            } while (type is not null);

            static_modifier = gen_source.IsMethodStatic ? "static" : string.Empty;
            _ = ce.AppendLine(@$"{ToKeyword(gen_source.MethodAccessibility)} {static_modifier} {Text_Regex} {gen_source.MethodName}()")
                  .AppendLine("{")
                  /**/ //TODO return single instance of the TextRegex object
                  .AppendLine("}");

            // TODO inject method source code here

            for (int i = 0; i < brace_count; i++)
            {
                _ = ce.AppendLine("}");
            }

            StringBuilder code_source = new();
            brace_count = 0;
            foreach (string line in ce)
            {
                bool is_right_brace = (line == "}") ||
                                      line.StartsWith("} while", StringComparison.InvariantCulture);
                brace_count -= is_right_brace ? 1 : 0;
                for (int i = 0; i < brace_count; i++) {
                    _ = code_source.Append("    ");
                }
                _ = code_source.AppendLine(line);
                brace_count += is_right_brace ? 0 : (line == "{" ? 1 : 0);
            }

            _ = file_name_sb.Append(CultureInfo.InvariantCulture, $@"{binding.Source.MethodName}.g.cs");
            string file_name = file_name_sb.ToString();
            context.AddSource(file_name, code_source.ToString());

            foreach (Diagnostic diag in binding.RegexDiagnostic) {
                context.ReportDiagnostic(diag);
            }
        }

        private static string ToKeyword(
                              Accessibility accessibility
        )
        {
            return accessibility switch
            {
                Accessibility.Public => "public",
                Accessibility.Private => "private",
                Accessibility.Internal => "internal",
                Accessibility.Protected => "protected",

                Accessibility.ProtectedAndInternal => "private protected",

                Accessibility.ProtectedOrInternal => "protected internal",

                _ => throw new InvalidOperationException(
                    $"Unexpected accessibility: {accessibility}"),
            };
        }

    }
}
