//-----------------------------------------------------------------------
// -----------------------------------------------------------------------
// file="glContext"
// Project: StgSharp
// AuthorGroup: Nitload
// Copyright (c) Nitload. All rights reserved.
//     
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//     
// -----------------------------------------------------------------------
// -----------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;

namespace StgSharp.Graphics.OpenGL
{
    public unsafe partial struct OpenglContext
    {

        internal unsafe delegate*<uint, uint, void> glActiveShaderProgram;
        internal unsafe delegate*<uint, void> glActiveTexture;
        internal unsafe delegate*<uint, uint, void> glAttachShader;
        internal unsafe delegate*<uint, uint, void> glBeginConditionalRender;
        internal unsafe delegate*<uint, uint, void> glBeginQuery;
        internal unsafe delegate*<uint, uint, uint, void> glBeginQueryIndexed;
        internal unsafe delegate*<uint, void> glBeginTransformFeedback;
        internal unsafe delegate*<uint, uint, byte*, void> glBindAttribLocation;
        internal unsafe delegate*<uint, uint, void> glBindBuffer;
        internal unsafe delegate*<uint, uint, uint, void> glBindBufferBase;
        internal unsafe delegate*<uint, uint, uint, nint, nuint, void> glBindBufferRange;
        internal unsafe delegate*<uint, uint, int, uint*, void> glBindBuffersBase;
        internal unsafe delegate*<uint, uint, int, uint*, nint*, nuint*, void> glBindBuffersRange;
        internal unsafe delegate*<uint, uint, byte*, void> glBindFragDataLocation;
        internal unsafe delegate*<uint, uint, uint, byte*, void> glBindFragDataLocationIndexed;
        internal unsafe delegate*<uint, uint, void> glBindFramebuffer;
        internal unsafe delegate*<uint, uint, int, byte, int, uint, uint, void> glBindImageTexture;
        internal unsafe delegate*<uint, int, uint*, void> glBindImageTextures;
        internal unsafe delegate*<uint, void> glBindProgramPipeline;
        internal unsafe delegate*<uint, uint, void> glBindRenderbuffer;
        internal unsafe delegate*<uint, uint, void> glBindSampler;
        internal unsafe delegate*<uint, int, uint*, void> glBindSamplers;
        internal unsafe delegate*<uint, uint, void> glBindTexture;
        internal unsafe delegate*<uint, int, uint*, void> glBindTextures;
        internal unsafe delegate*<uint, uint, void> glBindTextureUnit;
        internal unsafe delegate*<uint, uint, void> glBindTransformFeedback;
        internal unsafe delegate*<uint, void> glBindVertexArray;
        internal unsafe delegate*<uint, uint, nint, int, void> glBindVertexBuffer;
        internal unsafe delegate*<uint, int, uint*, nint*, int*, void> glBindVertexBuffers;
        internal unsafe delegate*<float, float, float, float, void> glBlendColor;
        internal unsafe delegate*<uint, void> glBlendEquation;
        internal unsafe delegate*<uint, uint, void> glBlendEquationi;
        internal unsafe delegate*<uint, uint, void> glBlendEquationSeparate;
        internal unsafe delegate*<uint, uint, uint, void> glBlendEquationSeparatei;
        internal unsafe delegate*<uint, uint, void> glBlendFunc;
        internal unsafe delegate*<uint, uint, uint, void> glBlendFunci;
        internal unsafe delegate*<uint, uint, uint, uint, void> glBlendFuncSeparate;
        internal unsafe delegate*<uint, uint, uint, uint, uint, void> glBlendFuncSeparatei;
        internal unsafe delegate*<int, int, int, int, int, int, int, int, uint, uint, void> glBlitFramebuffer;
        internal unsafe delegate*<uint, uint, int, int, int, int, int, int, int, int, uint, uint, void> glBlitNamedFramebuffer;
        internal unsafe delegate*<uint, nuint, IntPtr*, uint, void> glBufferData;
        internal unsafe delegate*<uint, nuint, IntPtr*, uint, void> glBufferStorage;
        internal unsafe delegate*<uint, nint, nuint, IntPtr*, void> glBufferSubData;
        internal unsafe delegate*<uint, uint> glCheckFramebufferStatus;
        internal unsafe delegate*<uint, uint, uint> glCheckNamedFramebufferStatus;
        internal unsafe delegate*<uint, uint, void> glClampColor;
        internal unsafe delegate*<uint, void> glClear;
        internal unsafe delegate*<uint, uint, uint, uint, IntPtr*, void> glClearBufferData;
        internal unsafe delegate*<uint, int, float, int, void> glClearBufferfi;
        internal unsafe delegate*<uint, int, float*, void> glClearBufferfv;
        internal unsafe delegate*<uint, int, int*, void> glClearBufferiv;
        internal unsafe delegate*<uint, uint, nint, nuint, uint, uint, IntPtr*, void> glClearBufferSubData;
        internal unsafe delegate*<uint, int, uint*, void> glClearBufferuiv;
        internal unsafe delegate*<float, float, float, float, void> glClearColor;
        internal unsafe delegate*<double, void> glClearDepth;
        internal unsafe delegate*<float, void> glClearDepthf;
        internal unsafe delegate*<uint, uint, uint, uint, IntPtr*, void> glClearNamedBufferData;
        internal unsafe delegate*<uint, uint, nint, nuint, uint, uint, IntPtr*, void> glClearNamedBufferSubData;
        internal unsafe delegate*<uint, uint, int, float, int, void> glClearNamedFramebufferfi;
        internal unsafe delegate*<uint, uint, int, float*, void> glClearNamedFramebufferfv;
        internal unsafe delegate*<uint, uint, int, int*, void> glClearNamedFramebufferiv;
        internal unsafe delegate*<uint, uint, int, uint*, void> glClearNamedFramebufferuiv;
        internal unsafe delegate*<int, void> glClearStencil;
        internal unsafe delegate*<uint, int, uint, uint, IntPtr*, void> glClearTexImage;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, uint, uint, IntPtr*, void> glClearTexSubImage;
        internal unsafe delegate*<glSync, uint, IntPtr, uint> glClientWaitSync;
        internal unsafe delegate*<uint, uint, void> glClipControl;
        internal unsafe delegate*<byte, byte, byte, byte, void> glColorMask;
        internal unsafe delegate*<uint, byte, byte, byte, byte, void> glColorMaski;
        internal unsafe delegate*<uint, void> glCompileShader;
        internal unsafe delegate*<uint, int, uint, int, int, int, IntPtr*, void> glCompressedTexImage1D;
        internal unsafe delegate*<uint, int, uint, int, int, int, int, IntPtr*, void> glCompressedTexImage2D;
        internal unsafe delegate*<uint, int, uint, int, int, int, int, int, IntPtr*, void> glCompressedTexImage3D;
        internal unsafe delegate*<uint, int, int, int, uint, int, IntPtr*, void> glCompressedTexSubImage1D;
        internal unsafe delegate*<uint, int, int, int, int, int, uint, int, IntPtr*, void> glCompressedTexSubImage2D;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, uint, int, IntPtr*, void> glCompressedTexSubImage3D;
        internal unsafe delegate*<uint, int, int, int, uint, int, IntPtr*, void> glCompressedTextureSubImage1D;
        internal unsafe delegate*<uint, int, int, int, int, int, uint, int, IntPtr*, void> glCompressedTextureSubImage2D;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, uint, int, IntPtr*, void> glCompressedTextureSubImage3D;
        internal unsafe delegate*<uint, uint, nint, nint, nuint, void> glCopyBufferSubData;
        internal unsafe delegate*<uint, uint, int, int, int, int, uint, uint, int, int, int, int, int, int, int, void> glCopyImageSubData;
        internal unsafe delegate*<uint, uint, nint, nint, nuint, void> glCopyNamedBufferSubData;
        internal unsafe delegate*<uint, int, uint, int, int, int, int, void> glCopyTexImage1D;
        internal unsafe delegate*<uint, int, uint, int, int, int, int, int, void> glCopyTexImage2D;
        internal unsafe delegate*<uint, int, int, int, int, int, void> glCopyTexSubImage1D;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, void> glCopyTexSubImage2D;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, int, void> glCopyTexSubImage3D;
        internal unsafe delegate*<uint, int, int, int, int, int, void> glCopyTextureSubImage1D;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, void> glCopyTextureSubImage2D;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, int, void> glCopyTextureSubImage3D;
        internal unsafe delegate*<int, uint*, void> glCreateBuffers;
        internal unsafe delegate*<int, uint*, void> glCreateFramebuffers;
        internal unsafe delegate*<uint> glCreateProgram;
        internal unsafe delegate*<int, uint*, void> glCreateProgramPipelines;
        internal unsafe delegate*<uint, int, uint*, void> glCreateQueries;
        internal unsafe delegate*<int, uint*, void> glCreateRenderbuffers;
        internal unsafe delegate*<int, uint*, void> glCreateSamplers;
        internal unsafe delegate*<uint, uint> glCreateShader;
        internal unsafe delegate*<uint, int, byte*, uint> glCreateShaderProgramv;
        internal unsafe delegate*<uint, int, uint*, void> glCreateTextures;
        internal unsafe delegate*<int, uint*, void> glCreateTransformFeedbacks;
        internal unsafe delegate*<int, uint*, void> glCreateVertexArrays;
        internal unsafe delegate*<uint, void> glCullFace;
        internal unsafe delegate*<IntPtr, IntPtr*, void> glDebugMessageCallback;
        internal unsafe delegate*<uint, uint, uint, int, uint*, byte, void> glDebugMessageControl;
        internal unsafe delegate*<uint, uint, uint, uint, int, byte*, void> glDebugMessageInsert;
        internal unsafe delegate*<int, uint*, void> glDeleteBuffers;
        internal unsafe delegate*<int, uint*, void> glDeleteFramebuffers;
        internal unsafe delegate*<uint, void> glDeleteProgram;
        internal unsafe delegate*<int, uint*, void> glDeleteProgramPipelines;
        internal unsafe delegate*<int, uint*, void> glDeleteQueries;
        internal unsafe delegate*<int, uint*, void> glDeleteRenderbuffers;
        internal unsafe delegate*<int, uint*, void> glDeleteSamplers;
        internal unsafe delegate*<uint, void> glDeleteShader;
        internal unsafe delegate*<glSync, void> glDeleteSync;
        internal unsafe delegate*<int, uint*, void> glDeleteTextures;
        internal unsafe delegate*<int, uint*, void> glDeleteTransformFeedbacks;
        internal unsafe delegate*<int, uint*, void> glDeleteVertexArrays;
        internal unsafe delegate*<uint, void> glDepthFunc;
        internal unsafe delegate*<byte, void> glDepthMask;
        internal unsafe delegate*<double, double, void> glDepthRange;
        internal unsafe delegate*<uint, int, double*, void> glDepthRangeArrayv;
        internal unsafe delegate*<float, float, void> glDepthRangef;
        internal unsafe delegate*<uint, double, double, void> glDepthRangeIndexed;
        internal unsafe delegate*<uint, uint, void> glDetachShader;
        internal unsafe delegate*<uint, void> glDisable;
        internal unsafe delegate*<uint, uint, void> glDisablei;
        internal unsafe delegate*<uint, uint, void> glDisableVertexArrayAttrib;
        internal unsafe delegate*<uint, void> glDisableVertexAttribArray;
        internal unsafe delegate*<uint, uint, uint, void> glDispatchCompute;
        internal unsafe delegate*<nint, void> glDispatchComputeIndirect;
        internal unsafe delegate*<uint, int, int, void> glDrawArrays;
        internal unsafe delegate*<uint, IntPtr*, void> glDrawArraysIndirect;
        internal unsafe delegate*<uint, int, int, int, void> glDrawArraysInstanced;
        internal unsafe delegate*<uint, int, int, int, uint, void> glDrawArraysInstancedBaseInstance;
        internal unsafe delegate*<uint, void> glDrawBuffer;
        internal unsafe delegate*<int, uint*, void> glDrawBuffers;
        internal unsafe delegate*<uint, int, uint, IntPtr*, void> glDrawElements;
        internal unsafe delegate*<uint, int, uint, IntPtr*, int, void> glDrawElementsBaseVertex;
        internal unsafe delegate*<uint, uint, IntPtr*, void> glDrawElementsIndirect;
        internal unsafe delegate*<uint, int, uint, IntPtr*, int, void> glDrawElementsInstanced;
        internal unsafe delegate*<uint, int, uint, IntPtr*, int, uint, void> glDrawElementsInstancedBaseInstance;
        internal unsafe delegate*<uint, int, uint, IntPtr*, int, int, void> glDrawElementsInstancedBaseVertex;
        internal unsafe delegate*<uint, int, uint, IntPtr*, int, int, uint, void> glDrawElementsInstancedBaseVertexBaseInstance;
        internal unsafe delegate*<uint, uint, uint, int, uint, IntPtr*, void> glDrawRangeElements;
        internal unsafe delegate*<uint, uint, uint, int, uint, IntPtr*, int, void> glDrawRangeElementsBaseVertex;
        internal unsafe delegate*<uint, uint, void> glDrawTransformFeedback;
        internal unsafe delegate*<uint, uint, int, void> glDrawTransformFeedbackInstanced;
        internal unsafe delegate*<uint, uint, uint, void> glDrawTransformFeedbackStream;
        internal unsafe delegate*<uint, uint, uint, int, void> glDrawTransformFeedbackStreamInstanced;
        internal unsafe delegate*<uint, void> glEnable;
        internal unsafe delegate*<uint, uint, void> glEnablei;
        internal unsafe delegate*<uint, uint, void> glEnableVertexArrayAttrib;
        internal unsafe delegate*<uint, void> glEnableVertexAttribArray;
        internal unsafe delegate*<void> glEndConditionalRender;
        internal unsafe delegate*<uint, void> glEndQuery;
        internal unsafe delegate*<uint, uint, void> glEndQueryIndexed;
        internal unsafe delegate*<void> glEndTransformFeedback;
        internal unsafe delegate*<uint, uint, glSync> glFenceSync;
        internal unsafe delegate*<void> glFinish;
        internal unsafe delegate*<void> glFlush;
        internal unsafe delegate*<uint, nint, nuint, void> glFlushMappedBufferRange;
        internal unsafe delegate*<uint, nint, nuint, void> glFlushMappedNamedBufferRange;
        internal unsafe delegate*<uint, uint, int, void> glFramebufferParameteri;
        internal unsafe delegate*<uint, uint, uint, uint, void> glFramebufferRenderbuffer;
        internal unsafe delegate*<uint, uint, uint, int, void> glFramebufferTexture;
        internal unsafe delegate*<uint, uint, uint, uint, int, void> glFramebufferTexture1D;
        internal unsafe delegate*<uint, uint, uint, uint, int, void> glFramebufferTexture2D;
        internal unsafe delegate*<uint, uint, uint, uint, int, int, void> glFramebufferTexture3D;
        internal unsafe delegate*<uint, uint, uint, int, int, void> glFramebufferTextureLayer;
        internal unsafe delegate*<uint, void> glFrontFace;
        internal unsafe delegate*<int, uint*, void> glGenBuffers;
        internal unsafe delegate*<uint, void> glGenerateMipmap;
        internal unsafe delegate*<uint, void> glGenerateTextureMipmap;
        internal unsafe delegate*<int, uint*, void> glGenFramebuffers;
        internal unsafe delegate*<int, uint*, void> glGenProgramPipelines;
        internal unsafe delegate*<int, uint*, void> glGenQueries;
        internal unsafe delegate*<int, uint*, void> glGenRenderbuffers;
        internal unsafe delegate*<int, uint*, void> glGenSamplers;
        internal unsafe delegate*<int, uint*, void> glGenTextures;
        internal unsafe delegate*<int, uint*, void> glGenTransformFeedbacks;
        internal unsafe delegate*<int, uint*, void> glGenVertexArrays;
        internal unsafe delegate*<uint, uint, uint, int*, void> glGetActiveAtomicCounterBufferiv;
        internal unsafe delegate*<uint, uint, int, int*, int*, uint*, byte*, void> glGetActiveAttrib;
        internal unsafe delegate*<uint, uint, uint, int, int*, byte*, void> glGetActiveSubroutineName;
        internal unsafe delegate*<uint, uint, uint, uint, int*, void> glGetActiveSubroutineUniformiv;
        internal unsafe delegate*<uint, uint, uint, int, int*, byte*, void> glGetActiveSubroutineUniformName;
        internal unsafe delegate*<uint, uint, int, int*, int*, uint*, byte*, void> glGetActiveUniform;
        internal unsafe delegate*<uint, uint, uint, int*, void> glGetActiveUniformBlockiv;
        internal unsafe delegate*<uint, uint, int, int*, byte*, void> glGetActiveUniformBlockName;
        internal unsafe delegate*<uint, uint, int, int*, byte*, void> glGetActiveUniformName;
        internal unsafe delegate*<uint, int, uint*, uint, int*, void> glGetActiveUniformsiv;
        internal unsafe delegate*<uint, int, int*, uint*, void> glGetAttachedShaders;
        internal unsafe delegate*<uint, byte*, int> glGetAttribLocation;
        internal unsafe delegate*<uint, uint, byte*, void> glGetBooleani_v;
        internal unsafe delegate*<uint, byte*, void> glGetBooleanv;
        internal unsafe delegate*<uint, uint, IntPtr*, void> glGetBufferParameteri64v;
        internal unsafe delegate*<uint, uint, int*, void> glGetBufferParameteriv;
        internal unsafe delegate*<uint, uint, IntPtr*, void> glGetBufferPointerv;
        internal unsafe delegate*<uint, nint, nuint, IntPtr*, void> glGetBufferSubData;
        internal unsafe delegate*<uint, int, IntPtr*, void> glGetCompressedTexImage;
        internal unsafe delegate*<uint, int, int, IntPtr*, void> glGetCompressedTextureImage;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, int, IntPtr*, void> glGetCompressedTextureSubImage;
        internal unsafe delegate*<uint, int, uint*, uint*, uint*, uint*, int*, byte*, uint> glGetDebugMessageLog;
        internal unsafe delegate*<uint, uint, double*, void> glGetDoublei_v;
        internal unsafe delegate*<uint, double*, void> glGetDoublev;
        internal unsafe delegate*<uint> glGetError;
        internal unsafe delegate*<uint, uint, float*, void> glGetFloati_v;
        internal unsafe delegate*<uint, float*, void> glGetFloatv;
        internal unsafe delegate*<uint, byte*, int> glGetFragDataIndex;
        internal unsafe delegate*<uint, byte*, int> glGetFragDataLocation;
        internal unsafe delegate*<uint, uint, uint, int*, void> glGetFramebufferAttachmentParameteriv;
        internal unsafe delegate*<uint, uint, int*, void> glGetFramebufferParameteriv;
        internal unsafe delegate*<uint> glGetGraphicsResetStatus;
        internal unsafe delegate*<uint, uint, IntPtr*, void> glGetInteger64i_v;
        internal unsafe delegate*<uint, IntPtr*, void> glGetInteger64v;
        internal unsafe delegate*<uint, uint, int*, void> glGetIntegeri_v;
        internal unsafe delegate*<uint, int*, void> glGetIntegerv;
        internal unsafe delegate*<uint, uint, uint, int, IntPtr*, void> glGetInternalformati64v;
        internal unsafe delegate*<uint, uint, uint, int, int*, void> glGetInternalformativ;
        internal unsafe delegate*<uint, uint, float*, void> glGetMultisamplefv;
        internal unsafe delegate*<uint, uint, IntPtr*, void> glGetNamedBufferParameteri64v;
        internal unsafe delegate*<uint, uint, int*, void> glGetNamedBufferParameteriv;
        internal unsafe delegate*<uint, uint, IntPtr*, void> glGetNamedBufferPointerv;
        internal unsafe delegate*<uint, nint, nuint, IntPtr*, void> glGetNamedBufferSubData;
        internal unsafe delegate*<uint, uint, uint, int*, void> glGetNamedFramebufferAttachmentParameteriv;
        internal unsafe delegate*<uint, uint, int*, void> glGetNamedFramebufferParameteriv;
        internal unsafe delegate*<uint, uint, int*, void> glGetNamedRenderbufferParameteriv;
        internal unsafe delegate*<uint, int, int, IntPtr*, void> glGetnCompressedTexImage;
        internal unsafe delegate*<uint, int, uint, uint, int, IntPtr*, void> glGetnTexImage;
        internal unsafe delegate*<uint, int, int, double*, void> glGetnUniformdv;
        internal unsafe delegate*<uint, int, int, float*, void> glGetnUniformfv;
        internal unsafe delegate*<uint, int, int, int*, void> glGetnUniformiv;
        internal unsafe delegate*<uint, int, int, uint*, void> glGetnUniformuiv;
        internal unsafe delegate*<uint, uint, int, int*, byte*, void> glGetObjectLabel;
        internal unsafe delegate*<IntPtr*, int, int*, byte*, void> glGetObjectPtrLabel;
        internal unsafe delegate*<uint, IntPtr*, void> glGetPointerv;
        internal unsafe delegate*<uint, int, int*, uint*, IntPtr*, void> glGetProgramBinary;
        internal unsafe delegate*<uint, int, int*, byte*, void> glGetProgramInfoLog;
        internal unsafe delegate*<uint, uint, uint, int*, void> glGetProgramInterfaceiv;
        internal unsafe delegate*<uint, uint, int*, void> glGetProgramiv;
        internal unsafe delegate*<uint, int, int*, byte*, void> glGetProgramPipelineInfoLog;
        internal unsafe delegate*<uint, uint, int*, void> glGetProgramPipelineiv;
        internal unsafe delegate*<uint, uint, byte*, uint> glGetProgramResourceIndex;
        internal unsafe delegate*<uint, uint, uint, int, uint*, int, int*, int*, void> glGetProgramResourceiv;
        internal unsafe delegate*<uint, uint, byte*, int> glGetProgramResourceLocation;
        internal unsafe delegate*<uint, uint, byte*, int> glGetProgramResourceLocationIndex;
        internal unsafe delegate*<uint, uint, uint, int, int*, byte*, void> glGetProgramResourceName;
        internal unsafe delegate*<uint, uint, uint, int*, void> glGetProgramStageiv;
        internal unsafe delegate*<uint, uint, uint, nint, void> glGetQueryBufferObjecti64v;
        internal unsafe delegate*<uint, uint, uint, nint, void> glGetQueryBufferObjectiv;
        internal unsafe delegate*<uint, uint, uint, nint, void> glGetQueryBufferObjectui64v;
        internal unsafe delegate*<uint, uint, uint, nint, void> glGetQueryBufferObjectuiv;
        internal unsafe delegate*<uint, uint, uint, int*, void> glGetQueryIndexediv;
        internal unsafe delegate*<uint, uint, int*, void> glGetQueryiv;
        internal unsafe delegate*<uint, uint, IntPtr*, void> glGetQueryObjecti64v;
        internal unsafe delegate*<uint, uint, int*, void> glGetQueryObjectiv;
        internal unsafe delegate*<uint, uint, IntPtr*, void> glGetQueryObjectui64v;
        internal unsafe delegate*<uint, uint, uint*, void> glGetQueryObjectuiv;
        internal unsafe delegate*<uint, uint, int*, void> glGetRenderbufferParameteriv;
        internal unsafe delegate*<uint, uint, float*, void> glGetSamplerParameterfv;
        internal unsafe delegate*<uint, uint, int*, void> glGetSamplerParameterIiv;
        internal unsafe delegate*<uint, uint, uint*, void> glGetSamplerParameterIuiv;
        internal unsafe delegate*<uint, uint, int*, void> glGetSamplerParameteriv;
        internal unsafe delegate*<uint, int, int*, byte*, void> glGetShaderInfoLog;
        internal unsafe delegate*<uint, uint, int*, void> glGetShaderiv;
        internal unsafe delegate*<uint, uint, int*, int*, void> glGetShaderPrecisionFormat;
        internal unsafe delegate*<uint, int, int*, byte*, void> glGetShaderSource;
        internal unsafe delegate*<uint, byte*> glGetString;
        internal unsafe delegate*<uint, uint, byte*> glGetStringi;
        internal unsafe delegate*<uint, uint, byte*, uint> glGetSubroutineIndex;
        internal unsafe delegate*<uint, uint, byte*, int> glGetSubroutineUniformLocation;
        internal unsafe delegate*<glSync, uint, int, int*, int*, void> glGetSynciv;
        internal unsafe delegate*<uint, int, uint, uint, IntPtr*, void> glGetTexImage;
        internal unsafe delegate*<uint, int, uint, float*, void> glGetTexLevelParameterfv;
        internal unsafe delegate*<uint, int, uint, int*, void> glGetTexLevelParameteriv;
        internal unsafe delegate*<uint, uint, float*, void> glGetTexParameterfv;
        internal unsafe delegate*<uint, uint, int*, void> glGetTexParameterIiv;
        internal unsafe delegate*<uint, uint, uint*, void> glGetTexParameterIuiv;
        internal unsafe delegate*<uint, uint, int*, void> glGetTexParameteriv;
        internal unsafe delegate*<uint, int, uint, uint, int, IntPtr*, void> glGetTextureImage;
        internal unsafe delegate*<uint, int, uint, float*, void> glGetTextureLevelParameterfv;
        internal unsafe delegate*<uint, int, uint, int*, void> glGetTextureLevelParameteriv;
        internal unsafe delegate*<uint, uint, float*, void> glGetTextureParameterfv;
        internal unsafe delegate*<uint, uint, int*, void> glGetTextureParameterIiv;
        internal unsafe delegate*<uint, uint, uint*, void> glGetTextureParameterIuiv;
        internal unsafe delegate*<uint, uint, int*, void> glGetTextureParameteriv;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, uint, uint, int, IntPtr*, void> glGetTextureSubImage;
        internal unsafe delegate*<uint, uint, uint, int*, void> glGetTransformFeedbacki_v;
        internal unsafe delegate*<uint, uint, uint, IntPtr*, void> glGetTransformFeedbacki64_v;
        internal unsafe delegate*<uint, uint, int*, void> glGetTransformFeedbackiv;
        internal unsafe delegate*<uint, uint, int, int*, int*, uint*, byte*, void> glGetTransformFeedbackVarying;
        internal unsafe delegate*<uint, byte*, uint> glGetUniformBlockIndex;
        internal unsafe delegate*<uint, int, double*, void> glGetUniformdv;
        internal unsafe delegate*<uint, int, float*, void> glGetUniformfv;
        internal unsafe delegate*<uint, int, byte*, uint*, void> glGetUniformIndices;
        internal unsafe delegate*<uint, int, int*, void> glGetUniformiv;
        internal unsafe delegate*<uint, byte*, int> glGetUniformLocation;
        internal unsafe delegate*<uint, int, uint*, void> glGetUniformSubroutineuiv;
        internal unsafe delegate*<uint, int, uint*, void> glGetUniformuiv;
        internal unsafe delegate*<uint, uint, uint, IntPtr*, void> glGetVertexArrayIndexed64iv;
        internal unsafe delegate*<uint, uint, uint, int*, void> glGetVertexArrayIndexediv;
        internal unsafe delegate*<uint, uint, int*, void> glGetVertexArrayiv;
        internal unsafe delegate*<uint, uint, double*, void> glGetVertexAttribdv;
        internal unsafe delegate*<uint, uint, float*, void> glGetVertexAttribfv;
        internal unsafe delegate*<uint, uint, int*, void> glGetVertexAttribIiv;
        internal unsafe delegate*<uint, uint, uint*, void> glGetVertexAttribIuiv;
        internal unsafe delegate*<uint, uint, int*, void> glGetVertexAttribiv;
        internal unsafe delegate*<uint, uint, double*, void> glGetVertexAttribLdv;
        internal unsafe delegate*<uint, uint, IntPtr*, void> glGetVertexAttribPointerv;
        internal unsafe delegate*<uint, uint, void> glHint;
        internal unsafe delegate*<uint, void> glInvalidateBufferData;
        internal unsafe delegate*<uint, nint, nuint, void> glInvalidateBufferSubData;
        internal unsafe delegate*<uint, int, uint*, void> glInvalidateFramebuffer;
        internal unsafe delegate*<uint, int, uint*, void> glInvalidateNamedFramebufferData;
        internal unsafe delegate*<uint, int, uint*, int, int, int, int, void> glInvalidateNamedFramebufferSubData;
        internal unsafe delegate*<uint, int, uint*, int, int, int, int, void> glInvalidateSubFramebuffer;
        internal unsafe delegate*<uint, int, void> glInvalidateTexImage;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, void> glInvalidateTexSubImage;
        internal unsafe delegate*<uint, byte> glIsBuffer;
        internal unsafe delegate*<uint, byte> glIsEnabled;
        internal unsafe delegate*<uint, uint, byte> glIsEnabledi;
        internal unsafe delegate*<uint, byte> glIsFramebuffer;
        internal unsafe delegate*<uint, byte> glIsProgram;
        internal unsafe delegate*<uint, byte> glIsProgramPipeline;
        internal unsafe delegate*<uint, byte> glIsQuery;
        internal unsafe delegate*<uint, byte> glIsRenderbuffer;
        internal unsafe delegate*<uint, byte> glIsSampler;
        internal unsafe delegate*<uint, byte> glIsShader;
        internal unsafe delegate*<glSync, byte> glIsSync;
        internal unsafe delegate*<uint, byte> glIsTexture;
        internal unsafe delegate*<uint, byte> glIsTransformFeedback;
        internal unsafe delegate*<uint, byte> glIsVertexArray;
        internal unsafe delegate*<float, void> glLineWidth;
        internal unsafe delegate*<uint, void> glLinkProgram;
        internal unsafe delegate*<uint, void> glLogicOp;
        internal unsafe delegate*<uint, uint, void*> glMapBuffer;
        internal unsafe delegate*<uint, nint, nuint, uint, void*> glMapBufferRange;
        internal unsafe delegate*<uint, uint, void*> glMapNamedBuffer;
        internal unsafe delegate*<uint, nint, nuint, uint, void*> glMapNamedBufferRange;
        internal unsafe delegate*<uint, void> glMemoryBarrier;
        internal unsafe delegate*<uint, void> glMemoryBarrierByRegion;
        internal unsafe delegate*<float, void> glMinSampleShading;
        internal unsafe delegate*<uint, int*, int*, int, void> glMultiDrawArrays;
        internal unsafe delegate*<uint, IntPtr*, int, int, void> glMultiDrawArraysIndirect;
        internal unsafe delegate*<uint, IntPtr*, nint, int, int, void> glMultiDrawArraysIndirectCount;
        internal unsafe delegate*<uint, int*, uint, IntPtr*, int, void> glMultiDrawElements;
        internal unsafe delegate*<uint, int*, uint, IntPtr*, int, int*, void> glMultiDrawElementsBaseVertex;
        internal unsafe delegate*<uint, uint, IntPtr*, int, int, void> glMultiDrawElementsIndirect;
        internal unsafe delegate*<uint, uint, IntPtr*, nint, int, int, void> glMultiDrawElementsIndirectCount;
        internal unsafe delegate*<uint, nuint, IntPtr*, uint, void> glNamedBufferData;
        internal unsafe delegate*<uint, nuint, IntPtr*, uint, void> glNamedBufferStorage;
        internal unsafe delegate*<uint, nint, nuint, IntPtr*, void> glNamedBufferSubData;
        internal unsafe delegate*<uint, uint, void> glNamedFramebufferDrawBuffer;
        internal unsafe delegate*<uint, int, uint*, void> glNamedFramebufferDrawBuffers;
        internal unsafe delegate*<uint, uint, int, void> glNamedFramebufferParameteri;
        internal unsafe delegate*<uint, uint, void> glNamedFramebufferReadBuffer;
        internal unsafe delegate*<uint, uint, uint, uint, void> glNamedFramebufferRenderbuffer;
        internal unsafe delegate*<uint, uint, uint, int, void> glNamedFramebufferTexture;
        internal unsafe delegate*<uint, uint, uint, int, int, void> glNamedFramebufferTextureLayer;
        internal unsafe delegate*<uint, uint, int, int, void> glNamedRenderbufferStorage;
        internal unsafe delegate*<uint, int, uint, int, int, void> glNamedRenderbufferStorageMultisample;
        internal unsafe delegate*<uint, uint, int, byte*, void> glObjectLabel;
        internal unsafe delegate*<IntPtr*, int, byte*, void> glObjectPtrLabel;
        internal unsafe delegate*<uint, float*, void> glPatchParameterfv;
        internal unsafe delegate*<uint, int, void> glPatchParameteri;
        internal unsafe delegate*<void> glPauseTransformFeedback;
        internal unsafe delegate*<uint, float, void> glPixelStoref;
        internal unsafe delegate*<uint, int, void> glPixelStorei;
        internal unsafe delegate*<uint, float, void> glPointParameterf;
        internal unsafe delegate*<uint, float*, void> glPointParameterfv;
        internal unsafe delegate*<uint, int, void> glPointParameteri;
        internal unsafe delegate*<uint, int*, void> glPointParameteriv;
        internal unsafe delegate*<float, void> glPointSize;
        internal unsafe delegate*<uint, uint, void> glPolygonMode;
        internal unsafe delegate*<float, float, void> glPolygonOffset;
        internal unsafe delegate*<float, float, float, void> glPolygonOffsetClamp;
        internal unsafe delegate*<void> glPopDebugGroup;
        internal unsafe delegate*<uint, void> glPrimitiveRestartIndex;
        internal unsafe delegate*<uint, uint, IntPtr*, int, void> glProgramBinary;
        internal unsafe delegate*<uint, uint, int, void> glProgramParameteri;
        internal unsafe delegate*<uint, int, double, void> glProgramUniform1d;
        internal unsafe delegate*<uint, int, int, double*, void> glProgramUniform1dv;
        internal unsafe delegate*<uint, int, float, void> glProgramUniform1f;
        internal unsafe delegate*<uint, int, int, float*, void> glProgramUniform1fv;
        internal unsafe delegate*<uint, int, int, void> glProgramUniform1i;
        internal unsafe delegate*<uint, int, int, int*, void> glProgramUniform1iv;
        internal unsafe delegate*<uint, int, uint, void> glProgramUniform1ui;
        internal unsafe delegate*<uint, int, int, uint*, void> glProgramUniform1uiv;
        internal unsafe delegate*<uint, int, double, double, void> glProgramUniform2d;
        internal unsafe delegate*<uint, int, int, double*, void> glProgramUniform2dv;
        internal unsafe delegate*<uint, int, float, float, void> glProgramUniform2f;
        internal unsafe delegate*<uint, int, int, float*, void> glProgramUniform2fv;
        internal unsafe delegate*<uint, int, int, int, void> glProgramUniform2i;
        internal unsafe delegate*<uint, int, int, int*, void> glProgramUniform2iv;
        internal unsafe delegate*<uint, int, uint, uint, void> glProgramUniform2ui;
        internal unsafe delegate*<uint, int, int, uint*, void> glProgramUniform2uiv;
        internal unsafe delegate*<uint, int, double, double, double, void> glProgramUniform3d;
        internal unsafe delegate*<uint, int, int, double*, void> glProgramUniform3dv;
        internal unsafe delegate*<uint, int, float, float, float, void> glProgramUniform3f;
        internal unsafe delegate*<uint, int, int, float*, void> glProgramUniform3fv;
        internal unsafe delegate*<uint, int, int, int, int, void> glProgramUniform3i;
        internal unsafe delegate*<uint, int, int, int*, void> glProgramUniform3iv;
        internal unsafe delegate*<uint, int, uint, uint, uint, void> glProgramUniform3ui;
        internal unsafe delegate*<uint, int, int, uint*, void> glProgramUniform3uiv;
        internal unsafe delegate*<uint, int, double, double, double, double, void> glProgramUniform4d;
        internal unsafe delegate*<uint, int, int, double*, void> glProgramUniform4dv;
        internal unsafe delegate*<uint, int, float, float, float, float, void> glProgramUniform4f;
        internal unsafe delegate*<uint, int, int, float*, void> glProgramUniform4fv;
        internal unsafe delegate*<uint, int, int, int, int, int, void> glProgramUniform4i;
        internal unsafe delegate*<uint, int, int, int*, void> glProgramUniform4iv;
        internal unsafe delegate*<uint, int, uint, uint, uint, uint, void> glProgramUniform4ui;
        internal unsafe delegate*<uint, int, int, uint*, void> glProgramUniform4uiv;
        internal unsafe delegate*<uint, int, int, byte, double*, void> glProgramUniformMatrix2dv;
        internal unsafe delegate*<uint, int, int, byte, float*, void> glProgramUniformMatrix2fv;
        internal unsafe delegate*<uint, int, int, byte, double*, void> glProgramUniformMatrix2x3dv;
        internal unsafe delegate*<uint, int, int, byte, float*, void> glProgramUniformMatrix2x3fv;
        internal unsafe delegate*<uint, int, int, byte, double*, void> glProgramUniformMatrix2x4dv;
        internal unsafe delegate*<uint, int, int, byte, float*, void> glProgramUniformMatrix2x4fv;
        internal unsafe delegate*<uint, int, int, byte, double*, void> glProgramUniformMatrix3dv;
        internal unsafe delegate*<uint, int, int, byte, float*, void> glProgramUniformMatrix3fv;
        internal unsafe delegate*<uint, int, int, byte, double*, void> glProgramUniformMatrix3x2dv;
        internal unsafe delegate*<uint, int, int, byte, float*, void> glProgramUniformMatrix3x2fv;
        internal unsafe delegate*<uint, int, int, byte, double*, void> glProgramUniformMatrix3x4dv;
        internal unsafe delegate*<uint, int, int, byte, float*, void> glProgramUniformMatrix3x4fv;
        internal unsafe delegate*<uint, int, int, byte, double*, void> glProgramUniformMatrix4dv;
        internal unsafe delegate*<uint, int, int, byte, float*, void> glProgramUniformMatrix4fv;
        internal unsafe delegate*<uint, int, int, byte, double*, void> glProgramUniformMatrix4x2dv;
        internal unsafe delegate*<uint, int, int, byte, float*, void> glProgramUniformMatrix4x2fv;
        internal unsafe delegate*<uint, int, int, byte, double*, void> glProgramUniformMatrix4x3dv;
        internal unsafe delegate*<uint, int, int, byte, float*, void> glProgramUniformMatrix4x3fv;
        internal unsafe delegate*<uint, void> glProvokingVertex;
        internal unsafe delegate*<uint, uint, int, byte*, void> glPushDebugGroup;
        internal unsafe delegate*<uint, uint, void> glQueryCounter;
        internal unsafe delegate*<uint, void> glReadBuffer;
        internal unsafe delegate*<int, int, int, int, uint, uint, int, IntPtr*, void> glReadnPixels;
        internal unsafe delegate*<int, int, int, int, uint, uint, IntPtr*, void> glReadPixels;
        internal unsafe delegate*<void> glReleaseShaderCompiler;
        internal unsafe delegate*<uint, uint, int, int, void> glRenderbufferStorage;
        internal unsafe delegate*<uint, int, uint, int, int, void> glRenderbufferStorageMultisample;
        internal unsafe delegate*<void> glResumeTransformFeedback;
        internal unsafe delegate*<float, byte, void> glSampleCoverage;
        internal unsafe delegate*<uint, uint, void> glSampleMaski;
        internal unsafe delegate*<uint, uint, float, void> glSamplerParameterf;
        internal unsafe delegate*<uint, uint, float*, void> glSamplerParameterfv;
        internal unsafe delegate*<uint, uint, int, void> glSamplerParameteri;
        internal unsafe delegate*<uint, uint, int*, void> glSamplerParameterIiv;
        internal unsafe delegate*<uint, uint, uint*, void> glSamplerParameterIuiv;
        internal unsafe delegate*<uint, uint, int*, void> glSamplerParameteriv;
        internal unsafe delegate*<int, int, int, int, void> glScissor;
        internal unsafe delegate*<uint, int, int*, void> glScissorArrayv;
        internal unsafe delegate*<uint, int, int, int, int, void> glScissorIndexed;
        internal unsafe delegate*<uint, int*, void> glScissorIndexedv;
        internal unsafe delegate*<int, uint*, uint, IntPtr*, int, void> glShaderBinary;
        internal unsafe delegate*<uint, int, byte**, int*, void> glShaderSource;
        internal unsafe delegate*<uint, uint, uint, void> glShaderStorageBlockBinding;
        internal unsafe delegate*<uint, byte*, uint, uint*, uint*, void> glSpecializeShader;
        internal unsafe delegate*<uint, int, uint, void> glStencilFunc;
        internal unsafe delegate*<uint, uint, int, uint, void> glStencilFuncSeparate;
        internal unsafe delegate*<uint, void> glStencilMask;
        internal unsafe delegate*<uint, uint, void> glStencilMaskSeparate;
        internal unsafe delegate*<uint, uint, uint, void> glStencilOp;
        internal unsafe delegate*<uint, uint, uint, uint, void> glStencilOpSeparate;
        internal unsafe delegate*<uint, uint, uint, void> glTexBuffer;
        internal unsafe delegate*<uint, uint, uint, nint, nuint, void> glTexBufferRange;
        internal unsafe delegate*<uint, int, int, int, int, uint, uint, IntPtr*, void> glTexImage1D;
        internal unsafe delegate*<uint, int, int, int, int, int, uint, uint, IntPtr*, void> glTexImage2D;
        internal unsafe delegate*<uint, int, uint, int, int, byte, void> glTexImage2DMultisample;
        internal unsafe delegate*<uint, int, int, int, int, int, int, uint, uint, IntPtr*, void> glTexImage3D;
        internal unsafe delegate*<uint, int, uint, int, int, int, byte, void> glTexImage3DMultisample;
        internal unsafe delegate*<uint, uint, float, void> glTexParameterf;
        internal unsafe delegate*<uint, uint, float*, void> glTexParameterfv;
        internal unsafe delegate*<uint, uint, int, void> glTexParameteri;
        internal unsafe delegate*<uint, uint, int*, void> glTexParameterIiv;
        internal unsafe delegate*<uint, uint, uint*, void> glTexParameterIuiv;
        internal unsafe delegate*<uint, uint, int*, void> glTexParameteriv;
        internal unsafe delegate*<uint, int, uint, int, void> glTexStorage1D;
        internal unsafe delegate*<uint, int, uint, int, int, void> glTexStorage2D;
        internal unsafe delegate*<uint, int, uint, int, int, byte, void> glTexStorage2DMultisample;
        internal unsafe delegate*<uint, int, uint, int, int, int, void> glTexStorage3D;
        internal unsafe delegate*<uint, int, uint, int, int, int, byte, void> glTexStorage3DMultisample;
        internal unsafe delegate*<uint, int, int, int, uint, uint, IntPtr*, void> glTexSubImage1D;
        internal unsafe delegate*<uint, int, int, int, int, int, uint, uint, IntPtr*, void> glTexSubImage2D;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, uint, uint, IntPtr*, void> glTexSubImage3D;
        internal unsafe delegate*<void> glTextureBarrier;
        internal unsafe delegate*<uint, uint, uint, void> glTextureBuffer;
        internal unsafe delegate*<uint, uint, uint, nint, nuint, void> glTextureBufferRange;
        internal unsafe delegate*<uint, uint, float, void> glTextureParameterf;
        internal unsafe delegate*<uint, uint, float*, void> glTextureParameterfv;
        internal unsafe delegate*<uint, uint, int, void> glTextureParameteri;
        internal unsafe delegate*<uint, uint, int*, void> glTextureParameterIiv;
        internal unsafe delegate*<uint, uint, uint*, void> glTextureParameterIuiv;
        internal unsafe delegate*<uint, uint, int*, void> glTextureParameteriv;
        internal unsafe delegate*<uint, int, uint, int, void> glTextureStorage1D;
        internal unsafe delegate*<uint, int, uint, int, int, void> glTextureStorage2D;
        internal unsafe delegate*<uint, int, uint, int, int, byte, void> glTextureStorage2DMultisample;
        internal unsafe delegate*<uint, int, uint, int, int, int, void> glTextureStorage3D;
        internal unsafe delegate*<uint, int, uint, int, int, int, byte, void> glTextureStorage3DMultisample;
        internal unsafe delegate*<uint, int, int, int, uint, uint, IntPtr*, void> glTextureSubImage1D;
        internal unsafe delegate*<uint, int, int, int, int, int, uint, uint, IntPtr*, void> glTextureSubImage2D;
        internal unsafe delegate*<uint, int, int, int, int, int, int, int, uint, uint, IntPtr*, void> glTextureSubImage3D;
        internal unsafe delegate*<uint, uint, uint, uint, uint, uint, uint, uint, void> glTextureView;
        internal unsafe delegate*<uint, uint, uint, void> glTransformFeedbackBufferBase;
        internal unsafe delegate*<uint, uint, uint, nint, nuint, void> glTransformFeedbackBufferRange;
        internal unsafe delegate*<uint, int, byte*, uint, void> glTransformFeedbackVaryings;
        internal unsafe delegate*<int, double, void> glUniform1d;
        internal unsafe delegate*<int, int, double*, void> glUniform1dv;
        internal unsafe delegate*<int, float, void> glUniform1f;
        internal unsafe delegate*<int, int, float*, void> glUniform1fv;
        internal unsafe delegate*<int, int, void> glUniform1i;
        internal unsafe delegate*<int, int, int*, void> glUniform1iv;
        internal unsafe delegate*<int, uint, void> glUniform1ui;
        internal unsafe delegate*<int, int, uint*, void> glUniform1uiv;
        internal unsafe delegate*<int, double, double, void> glUniform2d;
        internal unsafe delegate*<int, int, double*, void> glUniform2dv;
        internal unsafe delegate*<int, float, float, void> glUniform2f;
        internal unsafe delegate*<int, int, float*, void> glUniform2fv;
        internal unsafe delegate*<int, int, int, void> glUniform2i;
        internal unsafe delegate*<int, int, int*, void> glUniform2iv;
        internal unsafe delegate*<int, uint, uint, void> glUniform2ui;
        internal unsafe delegate*<int, int, uint*, void> glUniform2uiv;
        internal unsafe delegate*<int, double, double, double, void> glUniform3d;
        internal unsafe delegate*<int, int, double*, void> glUniform3dv;
        internal unsafe delegate*<int, float, float, float, void> glUniform3f;
        internal unsafe delegate*<int, int, float*, void> glUniform3fv;
        internal unsafe delegate*<int, int, int, int, void> glUniform3i;
        internal unsafe delegate*<int, int, int*, void> glUniform3iv;
        internal unsafe delegate*<int, uint, uint, uint, void> glUniform3ui;
        internal unsafe delegate*<int, int, uint*, void> glUniform3uiv;
        internal unsafe delegate*<int, double, double, double, double, void> glUniform4d;
        internal unsafe delegate*<int, int, double*, void> glUniform4dv;
        internal unsafe delegate*<int, float, float, float, float, void> glUniform4f;
        internal unsafe delegate*<int, int, float*, void> glUniform4fv;
        internal unsafe delegate*<int, int, int, int, int, void> glUniform4i;
        internal unsafe delegate*<int, int, int*, void> glUniform4iv;
        internal unsafe delegate*<int, uint, uint, uint, uint, void> glUniform4ui;
        internal unsafe delegate*<int, int, uint*, void> glUniform4uiv;
        internal unsafe delegate*<uint, uint, uint, void> glUniformBlockBinding;
        internal unsafe delegate*<int, int, byte, double*, void> glUniformMatrix2dv;
        internal unsafe delegate*<int, int, byte, float*, void> glUniformMatrix2fv;
        internal unsafe delegate*<int, int, byte, double*, void> glUniformMatrix2x3dv;
        internal unsafe delegate*<int, int, byte, float*, void> glUniformMatrix2x3fv;
        internal unsafe delegate*<int, int, byte, double*, void> glUniformMatrix2x4dv;
        internal unsafe delegate*<int, int, byte, float*, void> glUniformMatrix2x4fv;
        internal unsafe delegate*<int, int, byte, double*, void> glUniformMatrix3dv;
        internal unsafe delegate*<int, int, byte, float*, void> glUniformMatrix3fv;
        internal unsafe delegate*<int, int, byte, double*, void> glUniformMatrix3x2dv;
        internal unsafe delegate*<int, int, byte, float*, void> glUniformMatrix3x2fv;
        internal unsafe delegate*<int, int, byte, double*, void> glUniformMatrix3x4dv;
        internal unsafe delegate*<int, int, byte, float*, void> glUniformMatrix3x4fv;
        internal unsafe delegate*<int, int, byte, double*, void> glUniformMatrix4dv;
        internal unsafe delegate*<int, int, byte, float*, void> glUniformMatrix4fv;
        internal unsafe delegate*<int, int, byte, double*, void> glUniformMatrix4x2dv;
        internal unsafe delegate*<int, int, byte, float*, void> glUniformMatrix4x2fv;
        internal unsafe delegate*<int, int, byte, double*, void> glUniformMatrix4x3dv;
        internal unsafe delegate*<int, int, byte, float*, void> glUniformMatrix4x3fv;
        internal unsafe delegate*<uint, int, uint*, void> glUniformSubroutinesuiv;
        internal unsafe delegate*<uint, byte> glUnmapBuffer;
        internal unsafe delegate*<uint, byte> glUnmapNamedBuffer;
        internal unsafe delegate*<uint, void> glUseProgram;
        internal unsafe delegate*<uint, uint, uint, void> glUseProgramStages;
        internal unsafe delegate*<uint, void> glValidateProgram;
        internal unsafe delegate*<uint, void> glValidateProgramPipeline;
        internal unsafe delegate*<uint, uint, uint, void> glVertexArrayAttribBinding;
        internal unsafe delegate*<uint, uint, int, uint, byte, uint, void> glVertexArrayAttribFormat;
        internal unsafe delegate*<uint, uint, int, uint, uint, void> glVertexArrayAttribIFormat;
        internal unsafe delegate*<uint, uint, int, uint, uint, void> glVertexArrayAttribLFormat;
        internal unsafe delegate*<uint, uint, uint, void> glVertexArrayBindingDivisor;
        internal unsafe delegate*<uint, uint, void> glVertexArrayElementBuffer;
        internal unsafe delegate*<uint, uint, uint, nint, int, void> glVertexArrayVertexBuffer;
        internal unsafe delegate*<uint, uint, int, uint*, nint*, int*, void> glVertexArrayVertexBuffers;
        internal unsafe delegate*<uint, double, void> glVertexAttrib1d;
        internal unsafe delegate*<uint, double*, void> glVertexAttrib1dv;
        internal unsafe delegate*<uint, float, void> glVertexAttrib1f;
        internal unsafe delegate*<uint, float*, void> glVertexAttrib1fv;
        internal unsafe delegate*<uint, short, void> glVertexAttrib1s;
        internal unsafe delegate*<uint, short*, void> glVertexAttrib1sv;
        internal unsafe delegate*<uint, double, double, void> glVertexAttrib2d;
        internal unsafe delegate*<uint, double*, void> glVertexAttrib2dv;
        internal unsafe delegate*<uint, float, float, void> glVertexAttrib2f;
        internal unsafe delegate*<uint, float*, void> glVertexAttrib2fv;
        internal unsafe delegate*<uint, short, short, void> glVertexAttrib2s;
        internal unsafe delegate*<uint, short*, void> glVertexAttrib2sv;
        internal unsafe delegate*<uint, double, double, double, void> glVertexAttrib3d;
        internal unsafe delegate*<uint, double*, void> glVertexAttrib3dv;
        internal unsafe delegate*<uint, float, float, float, void> glVertexAttrib3f;
        internal unsafe delegate*<uint, float*, void> glVertexAttrib3fv;
        internal unsafe delegate*<uint, short, short, short, void> glVertexAttrib3s;
        internal unsafe delegate*<uint, short*, void> glVertexAttrib3sv;
        internal unsafe delegate*<uint, sbyte*, void> glVertexAttrib4bv;
        internal unsafe delegate*<uint, double, double, double, double, void> glVertexAttrib4d;
        internal unsafe delegate*<uint, double*, void> glVertexAttrib4dv;
        internal unsafe delegate*<uint, float, float, float, float, void> glVertexAttrib4f;
        internal unsafe delegate*<uint, float*, void> glVertexAttrib4fv;
        internal unsafe delegate*<uint, int*, void> glVertexAttrib4iv;
        internal unsafe delegate*<uint, sbyte*, void> glVertexAttrib4Nbv;
        internal unsafe delegate*<uint, int*, void> glVertexAttrib4Niv;
        internal unsafe delegate*<uint, short*, void> glVertexAttrib4Nsv;
        internal unsafe delegate*<uint, byte, byte, byte, byte, void> glVertexAttrib4Nub;
        internal unsafe delegate*<uint, byte*, void> glVertexAttrib4Nubv;
        internal unsafe delegate*<uint, uint*, void> glVertexAttrib4Nuiv;
        internal unsafe delegate*<uint, ushort*, void> glVertexAttrib4Nusv;
        internal unsafe delegate*<uint, short, short, short, short, void> glVertexAttrib4s;
        internal unsafe delegate*<uint, short*, void> glVertexAttrib4sv;
        internal unsafe delegate*<uint, byte*, void> glVertexAttrib4ubv;
        internal unsafe delegate*<uint, uint*, void> glVertexAttrib4uiv;
        internal unsafe delegate*<uint, ushort*, void> glVertexAttrib4usv;
        internal unsafe delegate*<uint, uint, void> glVertexAttribBinding;
        internal unsafe delegate*<uint, uint, void> glVertexAttribDivisor;
        internal unsafe delegate*<uint, int, uint, byte, uint, void> glVertexAttribFormat;
        internal unsafe delegate*<uint, int, void> glVertexAttribI1i;
        internal unsafe delegate*<uint, int*, void> glVertexAttribI1iv;
        internal unsafe delegate*<uint, uint, void> glVertexAttribI1ui;
        internal unsafe delegate*<uint, uint*, void> glVertexAttribI1uiv;
        internal unsafe delegate*<uint, int, int, void> glVertexAttribI2i;
        internal unsafe delegate*<uint, int*, void> glVertexAttribI2iv;
        internal unsafe delegate*<uint, uint, uint, void> glVertexAttribI2ui;
        internal unsafe delegate*<uint, uint*, void> glVertexAttribI2uiv;
        internal unsafe delegate*<uint, int, int, int, void> glVertexAttribI3i;
        internal unsafe delegate*<uint, int*, void> glVertexAttribI3iv;
        internal unsafe delegate*<uint, uint, uint, uint, void> glVertexAttribI3ui;
        internal unsafe delegate*<uint, uint*, void> glVertexAttribI3uiv;
        internal unsafe delegate*<uint, sbyte*, void> glVertexAttribI4bv;
        internal unsafe delegate*<uint, int, int, int, int, void> glVertexAttribI4i;
        internal unsafe delegate*<uint, int*, void> glVertexAttribI4iv;
        internal unsafe delegate*<uint, short*, void> glVertexAttribI4sv;
        internal unsafe delegate*<uint, byte*, void> glVertexAttribI4ubv;
        internal unsafe delegate*<uint, uint, uint, uint, uint, void> glVertexAttribI4ui;
        internal unsafe delegate*<uint, uint*, void> glVertexAttribI4uiv;
        internal unsafe delegate*<uint, ushort*, void> glVertexAttribI4usv;
        internal unsafe delegate*<uint, int, uint, uint, void> glVertexAttribIFormat;
        internal unsafe delegate*<uint, int, uint, int, IntPtr*, void> glVertexAttribIPointer;
        internal unsafe delegate*<uint, double, void> glVertexAttribL1d;
        internal unsafe delegate*<uint, double*, void> glVertexAttribL1dv;
        internal unsafe delegate*<uint, double, double, void> glVertexAttribL2d;
        internal unsafe delegate*<uint, double*, void> glVertexAttribL2dv;
        internal unsafe delegate*<uint, double, double, double, void> glVertexAttribL3d;
        internal unsafe delegate*<uint, double*, void> glVertexAttribL3dv;
        internal unsafe delegate*<uint, double, double, double, double, void> glVertexAttribL4d;
        internal unsafe delegate*<uint, double*, void> glVertexAttribL4dv;
        internal unsafe delegate*<uint, int, uint, uint, void> glVertexAttribLFormat;
        internal unsafe delegate*<uint, int, uint, int, IntPtr*, void> glVertexAttribLPointer;
        internal unsafe delegate*<uint, uint, byte, uint, void> glVertexAttribP1ui;
        internal unsafe delegate*<uint, uint, byte, uint*, void> glVertexAttribP1uiv;
        internal unsafe delegate*<uint, uint, byte, uint, void> glVertexAttribP2ui;
        internal unsafe delegate*<uint, uint, byte, uint*, void> glVertexAttribP2uiv;
        internal unsafe delegate*<uint, uint, byte, uint, void> glVertexAttribP3ui;
        internal unsafe delegate*<uint, uint, byte, uint*, void> glVertexAttribP3uiv;
        internal unsafe delegate*<uint, uint, byte, uint, void> glVertexAttribP4ui;
        internal unsafe delegate*<uint, uint, byte, uint*, void> glVertexAttribP4uiv;
        internal unsafe delegate*<uint, int, uint, byte, int, IntPtr*, void> glVertexAttribPointer;
        internal unsafe delegate*<uint, uint, void> glVertexBindingDivisor;
        internal unsafe delegate*<int, int, int, int, void> glViewport;
        internal unsafe delegate*<uint, int, float*, void> glViewportArrayv;
        internal unsafe delegate*<uint, float, float, float, float, void> glViewportIndexedf;
        internal unsafe delegate*<uint, float*, void> glViewportIndexedfv;
        internal unsafe delegate*<glSync, uint, IntPtr, void> glWaitSync;

    }
}
